#ifndef _ALTERA_HPS_0_H_
#define _ALTERA_HPS_0_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'soc_system' in
 * file './soc_system.sopcinfo'.
 */

/*
 * This file contains macros for module 'hps_0' and devices
 * connected to the following masters:
 *   h2f_axi_master
 *   h2f_lw_axi_master
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'onchip_memory2_0', class 'altera_avalon_onchip_memory2'
 * The macros are prefixed with 'ONCHIP_MEMORY2_0_'.
 * The prefix is the slave descriptor.
 */
#define ONCHIP_MEMORY2_0_COMPONENT_TYPE altera_avalon_onchip_memory2
#define ONCHIP_MEMORY2_0_COMPONENT_NAME onchip_memory2_0
#define ONCHIP_MEMORY2_0_BASE 0x0
#define ONCHIP_MEMORY2_0_SPAN 65536
#define ONCHIP_MEMORY2_0_END 0xffff
#define ONCHIP_MEMORY2_0_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define ONCHIP_MEMORY2_0_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define ONCHIP_MEMORY2_0_CONTENTS_INFO ""
#define ONCHIP_MEMORY2_0_DUAL_PORT 0
#define ONCHIP_MEMORY2_0_GUI_RAM_BLOCK_TYPE AUTO
#define ONCHIP_MEMORY2_0_INIT_CONTENTS_FILE soc_system_onchip_memory2_0
#define ONCHIP_MEMORY2_0_INIT_MEM_CONTENT 1
#define ONCHIP_MEMORY2_0_INSTANCE_ID NONE
#define ONCHIP_MEMORY2_0_NON_DEFAULT_INIT_FILE_ENABLED 0
#define ONCHIP_MEMORY2_0_RAM_BLOCK_TYPE AUTO
#define ONCHIP_MEMORY2_0_READ_DURING_WRITE_MODE DONT_CARE
#define ONCHIP_MEMORY2_0_SINGLE_CLOCK_OP 0
#define ONCHIP_MEMORY2_0_SIZE_MULTIPLE 1
#define ONCHIP_MEMORY2_0_SIZE_VALUE 65536
#define ONCHIP_MEMORY2_0_WRITABLE 1
#define ONCHIP_MEMORY2_0_MEMORY_INFO_DAT_SYM_INSTALL_DIR SIM_DIR
#define ONCHIP_MEMORY2_0_MEMORY_INFO_GENERATE_DAT_SYM 1
#define ONCHIP_MEMORY2_0_MEMORY_INFO_GENERATE_HEX 1
#define ONCHIP_MEMORY2_0_MEMORY_INFO_HAS_BYTE_LANE 0
#define ONCHIP_MEMORY2_0_MEMORY_INFO_HEX_INSTALL_DIR QPF_DIR
#define ONCHIP_MEMORY2_0_MEMORY_INFO_MEM_INIT_DATA_WIDTH 64
#define ONCHIP_MEMORY2_0_MEMORY_INFO_MEM_INIT_FILENAME soc_system_onchip_memory2_0

/*
 * Macros for device 'a_0', class 'altera_avalon_pio'
 * The macros are prefixed with 'A_0_'.
 * The prefix is the slave descriptor.
 */
#define A_0_COMPONENT_TYPE altera_avalon_pio
#define A_0_COMPONENT_NAME a_0
#define A_0_BASE 0x0
#define A_0_SPAN 16
#define A_0_END 0xf
#define A_0_BIT_CLEARING_EDGE_REGISTER 0
#define A_0_BIT_MODIFYING_OUTPUT_REGISTER 0
#define A_0_CAPTURE 0
#define A_0_DATA_WIDTH 8
#define A_0_DO_TEST_BENCH_WIRING 0
#define A_0_DRIVEN_SIM_VALUE 0
#define A_0_EDGE_TYPE NONE
#define A_0_FREQ 50000000
#define A_0_HAS_IN 0
#define A_0_HAS_OUT 1
#define A_0_HAS_TRI 0
#define A_0_IRQ_TYPE NONE
#define A_0_RESET_VALUE 255

/*
 * Macros for device 'a_1', class 'altera_avalon_pio'
 * The macros are prefixed with 'A_1_'.
 * The prefix is the slave descriptor.
 */
#define A_1_COMPONENT_TYPE altera_avalon_pio
#define A_1_COMPONENT_NAME a_1
#define A_1_BASE 0x10
#define A_1_SPAN 16
#define A_1_END 0x1f
#define A_1_BIT_CLEARING_EDGE_REGISTER 0
#define A_1_BIT_MODIFYING_OUTPUT_REGISTER 0
#define A_1_CAPTURE 0
#define A_1_DATA_WIDTH 8
#define A_1_DO_TEST_BENCH_WIRING 0
#define A_1_DRIVEN_SIM_VALUE 0
#define A_1_EDGE_TYPE NONE
#define A_1_FREQ 50000000
#define A_1_HAS_IN 0
#define A_1_HAS_OUT 1
#define A_1_HAS_TRI 0
#define A_1_IRQ_TYPE NONE
#define A_1_RESET_VALUE 255

/*
 * Macros for device 'a_2', class 'altera_avalon_pio'
 * The macros are prefixed with 'A_2_'.
 * The prefix is the slave descriptor.
 */
#define A_2_COMPONENT_TYPE altera_avalon_pio
#define A_2_COMPONENT_NAME a_2
#define A_2_BASE 0x20
#define A_2_SPAN 16
#define A_2_END 0x2f
#define A_2_BIT_CLEARING_EDGE_REGISTER 0
#define A_2_BIT_MODIFYING_OUTPUT_REGISTER 0
#define A_2_CAPTURE 0
#define A_2_DATA_WIDTH 8
#define A_2_DO_TEST_BENCH_WIRING 0
#define A_2_DRIVEN_SIM_VALUE 0
#define A_2_EDGE_TYPE NONE
#define A_2_FREQ 50000000
#define A_2_HAS_IN 0
#define A_2_HAS_OUT 1
#define A_2_HAS_TRI 0
#define A_2_IRQ_TYPE NONE
#define A_2_RESET_VALUE 255

/*
 * Macros for device 'a_3', class 'altera_avalon_pio'
 * The macros are prefixed with 'A_3_'.
 * The prefix is the slave descriptor.
 */
#define A_3_COMPONENT_TYPE altera_avalon_pio
#define A_3_COMPONENT_NAME a_3
#define A_3_BASE 0x30
#define A_3_SPAN 16
#define A_3_END 0x3f
#define A_3_BIT_CLEARING_EDGE_REGISTER 0
#define A_3_BIT_MODIFYING_OUTPUT_REGISTER 0
#define A_3_CAPTURE 0
#define A_3_DATA_WIDTH 8
#define A_3_DO_TEST_BENCH_WIRING 0
#define A_3_DRIVEN_SIM_VALUE 0
#define A_3_EDGE_TYPE NONE
#define A_3_FREQ 50000000
#define A_3_HAS_IN 0
#define A_3_HAS_OUT 1
#define A_3_HAS_TRI 0
#define A_3_IRQ_TYPE NONE
#define A_3_RESET_VALUE 255

/*
 * Macros for device 'b_0', class 'altera_avalon_pio'
 * The macros are prefixed with 'B_0_'.
 * The prefix is the slave descriptor.
 */
#define B_0_COMPONENT_TYPE altera_avalon_pio
#define B_0_COMPONENT_NAME b_0
#define B_0_BASE 0x40
#define B_0_SPAN 16
#define B_0_END 0x4f
#define B_0_BIT_CLEARING_EDGE_REGISTER 0
#define B_0_BIT_MODIFYING_OUTPUT_REGISTER 0
#define B_0_CAPTURE 0
#define B_0_DATA_WIDTH 8
#define B_0_DO_TEST_BENCH_WIRING 0
#define B_0_DRIVEN_SIM_VALUE 0
#define B_0_EDGE_TYPE NONE
#define B_0_FREQ 50000000
#define B_0_HAS_IN 0
#define B_0_HAS_OUT 1
#define B_0_HAS_TRI 0
#define B_0_IRQ_TYPE NONE
#define B_0_RESET_VALUE 255

/*
 * Macros for device 'b_1', class 'altera_avalon_pio'
 * The macros are prefixed with 'B_1_'.
 * The prefix is the slave descriptor.
 */
#define B_1_COMPONENT_TYPE altera_avalon_pio
#define B_1_COMPONENT_NAME b_1
#define B_1_BASE 0x50
#define B_1_SPAN 16
#define B_1_END 0x5f
#define B_1_BIT_CLEARING_EDGE_REGISTER 0
#define B_1_BIT_MODIFYING_OUTPUT_REGISTER 0
#define B_1_CAPTURE 0
#define B_1_DATA_WIDTH 8
#define B_1_DO_TEST_BENCH_WIRING 0
#define B_1_DRIVEN_SIM_VALUE 0
#define B_1_EDGE_TYPE NONE
#define B_1_FREQ 50000000
#define B_1_HAS_IN 0
#define B_1_HAS_OUT 1
#define B_1_HAS_TRI 0
#define B_1_IRQ_TYPE NONE
#define B_1_RESET_VALUE 255

/*
 * Macros for device 'b_2', class 'altera_avalon_pio'
 * The macros are prefixed with 'B_2_'.
 * The prefix is the slave descriptor.
 */
#define B_2_COMPONENT_TYPE altera_avalon_pio
#define B_2_COMPONENT_NAME b_2
#define B_2_BASE 0x60
#define B_2_SPAN 16
#define B_2_END 0x6f
#define B_2_BIT_CLEARING_EDGE_REGISTER 0
#define B_2_BIT_MODIFYING_OUTPUT_REGISTER 0
#define B_2_CAPTURE 0
#define B_2_DATA_WIDTH 8
#define B_2_DO_TEST_BENCH_WIRING 0
#define B_2_DRIVEN_SIM_VALUE 0
#define B_2_EDGE_TYPE NONE
#define B_2_FREQ 50000000
#define B_2_HAS_IN 0
#define B_2_HAS_OUT 1
#define B_2_HAS_TRI 0
#define B_2_IRQ_TYPE NONE
#define B_2_RESET_VALUE 255

/*
 * Macros for device 'b_3', class 'altera_avalon_pio'
 * The macros are prefixed with 'B_3_'.
 * The prefix is the slave descriptor.
 */
#define B_3_COMPONENT_TYPE altera_avalon_pio
#define B_3_COMPONENT_NAME b_3
#define B_3_BASE 0x70
#define B_3_SPAN 16
#define B_3_END 0x7f
#define B_3_BIT_CLEARING_EDGE_REGISTER 0
#define B_3_BIT_MODIFYING_OUTPUT_REGISTER 0
#define B_3_CAPTURE 0
#define B_3_DATA_WIDTH 8
#define B_3_DO_TEST_BENCH_WIRING 0
#define B_3_DRIVEN_SIM_VALUE 0
#define B_3_EDGE_TYPE NONE
#define B_3_FREQ 50000000
#define B_3_HAS_IN 0
#define B_3_HAS_OUT 1
#define B_3_HAS_TRI 0
#define B_3_IRQ_TYPE NONE
#define B_3_RESET_VALUE 255

/*
 * Macros for device 'out_0', class 'altera_avalon_pio'
 * The macros are prefixed with 'OUT_0_'.
 * The prefix is the slave descriptor.
 */
#define OUT_0_COMPONENT_TYPE altera_avalon_pio
#define OUT_0_COMPONENT_NAME out_0
#define OUT_0_BASE 0x80
#define OUT_0_SPAN 16
#define OUT_0_END 0x8f
#define OUT_0_BIT_CLEARING_EDGE_REGISTER 0
#define OUT_0_BIT_MODIFYING_OUTPUT_REGISTER 0
#define OUT_0_CAPTURE 0
#define OUT_0_DATA_WIDTH 19
#define OUT_0_DO_TEST_BENCH_WIRING 0
#define OUT_0_DRIVEN_SIM_VALUE 0
#define OUT_0_EDGE_TYPE NONE
#define OUT_0_FREQ 50000000
#define OUT_0_HAS_IN 1
#define OUT_0_HAS_OUT 0
#define OUT_0_HAS_TRI 0
#define OUT_0_IRQ_TYPE NONE
#define OUT_0_RESET_VALUE 0

/*
 * Macros for device 'a_4', class 'altera_avalon_pio'
 * The macros are prefixed with 'A_4_'.
 * The prefix is the slave descriptor.
 */
#define A_4_COMPONENT_TYPE altera_avalon_pio
#define A_4_COMPONENT_NAME a_4
#define A_4_BASE 0x90
#define A_4_SPAN 16
#define A_4_END 0x9f
#define A_4_BIT_CLEARING_EDGE_REGISTER 0
#define A_4_BIT_MODIFYING_OUTPUT_REGISTER 0
#define A_4_CAPTURE 0
#define A_4_DATA_WIDTH 8
#define A_4_DO_TEST_BENCH_WIRING 0
#define A_4_DRIVEN_SIM_VALUE 0
#define A_4_EDGE_TYPE NONE
#define A_4_FREQ 50000000
#define A_4_HAS_IN 0
#define A_4_HAS_OUT 1
#define A_4_HAS_TRI 0
#define A_4_IRQ_TYPE NONE
#define A_4_RESET_VALUE 255

/*
 * Macros for device 'a_5', class 'altera_avalon_pio'
 * The macros are prefixed with 'A_5_'.
 * The prefix is the slave descriptor.
 */
#define A_5_COMPONENT_TYPE altera_avalon_pio
#define A_5_COMPONENT_NAME a_5
#define A_5_BASE 0xa0
#define A_5_SPAN 16
#define A_5_END 0xaf
#define A_5_BIT_CLEARING_EDGE_REGISTER 0
#define A_5_BIT_MODIFYING_OUTPUT_REGISTER 0
#define A_5_CAPTURE 0
#define A_5_DATA_WIDTH 8
#define A_5_DO_TEST_BENCH_WIRING 0
#define A_5_DRIVEN_SIM_VALUE 0
#define A_5_EDGE_TYPE NONE
#define A_5_FREQ 50000000
#define A_5_HAS_IN 0
#define A_5_HAS_OUT 1
#define A_5_HAS_TRI 0
#define A_5_IRQ_TYPE NONE
#define A_5_RESET_VALUE 255

/*
 * Macros for device 'a_6', class 'altera_avalon_pio'
 * The macros are prefixed with 'A_6_'.
 * The prefix is the slave descriptor.
 */
#define A_6_COMPONENT_TYPE altera_avalon_pio
#define A_6_COMPONENT_NAME a_6
#define A_6_BASE 0xb0
#define A_6_SPAN 16
#define A_6_END 0xbf
#define A_6_BIT_CLEARING_EDGE_REGISTER 0
#define A_6_BIT_MODIFYING_OUTPUT_REGISTER 0
#define A_6_CAPTURE 0
#define A_6_DATA_WIDTH 8
#define A_6_DO_TEST_BENCH_WIRING 0
#define A_6_DRIVEN_SIM_VALUE 0
#define A_6_EDGE_TYPE NONE
#define A_6_FREQ 50000000
#define A_6_HAS_IN 0
#define A_6_HAS_OUT 1
#define A_6_HAS_TRI 0
#define A_6_IRQ_TYPE NONE
#define A_6_RESET_VALUE 255

/*
 * Macros for device 'a_7', class 'altera_avalon_pio'
 * The macros are prefixed with 'A_7_'.
 * The prefix is the slave descriptor.
 */
#define A_7_COMPONENT_TYPE altera_avalon_pio
#define A_7_COMPONENT_NAME a_7
#define A_7_BASE 0xc0
#define A_7_SPAN 16
#define A_7_END 0xcf
#define A_7_BIT_CLEARING_EDGE_REGISTER 0
#define A_7_BIT_MODIFYING_OUTPUT_REGISTER 0
#define A_7_CAPTURE 0
#define A_7_DATA_WIDTH 8
#define A_7_DO_TEST_BENCH_WIRING 0
#define A_7_DRIVEN_SIM_VALUE 0
#define A_7_EDGE_TYPE NONE
#define A_7_FREQ 50000000
#define A_7_HAS_IN 0
#define A_7_HAS_OUT 1
#define A_7_HAS_TRI 0
#define A_7_IRQ_TYPE NONE
#define A_7_RESET_VALUE 255

/*
 * Macros for device 'b_4', class 'altera_avalon_pio'
 * The macros are prefixed with 'B_4_'.
 * The prefix is the slave descriptor.
 */
#define B_4_COMPONENT_TYPE altera_avalon_pio
#define B_4_COMPONENT_NAME b_4
#define B_4_BASE 0xd0
#define B_4_SPAN 16
#define B_4_END 0xdf
#define B_4_BIT_CLEARING_EDGE_REGISTER 0
#define B_4_BIT_MODIFYING_OUTPUT_REGISTER 0
#define B_4_CAPTURE 0
#define B_4_DATA_WIDTH 8
#define B_4_DO_TEST_BENCH_WIRING 0
#define B_4_DRIVEN_SIM_VALUE 0
#define B_4_EDGE_TYPE NONE
#define B_4_FREQ 50000000
#define B_4_HAS_IN 0
#define B_4_HAS_OUT 1
#define B_4_HAS_TRI 0
#define B_4_IRQ_TYPE NONE
#define B_4_RESET_VALUE 255

/*
 * Macros for device 'b_5', class 'altera_avalon_pio'
 * The macros are prefixed with 'B_5_'.
 * The prefix is the slave descriptor.
 */
#define B_5_COMPONENT_TYPE altera_avalon_pio
#define B_5_COMPONENT_NAME b_5
#define B_5_BASE 0xe0
#define B_5_SPAN 16
#define B_5_END 0xef
#define B_5_BIT_CLEARING_EDGE_REGISTER 0
#define B_5_BIT_MODIFYING_OUTPUT_REGISTER 0
#define B_5_CAPTURE 0
#define B_5_DATA_WIDTH 8
#define B_5_DO_TEST_BENCH_WIRING 0
#define B_5_DRIVEN_SIM_VALUE 0
#define B_5_EDGE_TYPE NONE
#define B_5_FREQ 50000000
#define B_5_HAS_IN 0
#define B_5_HAS_OUT 1
#define B_5_HAS_TRI 0
#define B_5_IRQ_TYPE NONE
#define B_5_RESET_VALUE 255

/*
 * Macros for device 'b_6', class 'altera_avalon_pio'
 * The macros are prefixed with 'B_6_'.
 * The prefix is the slave descriptor.
 */
#define B_6_COMPONENT_TYPE altera_avalon_pio
#define B_6_COMPONENT_NAME b_6
#define B_6_BASE 0xf0
#define B_6_SPAN 16
#define B_6_END 0xff
#define B_6_BIT_CLEARING_EDGE_REGISTER 0
#define B_6_BIT_MODIFYING_OUTPUT_REGISTER 0
#define B_6_CAPTURE 0
#define B_6_DATA_WIDTH 8
#define B_6_DO_TEST_BENCH_WIRING 0
#define B_6_DRIVEN_SIM_VALUE 0
#define B_6_EDGE_TYPE NONE
#define B_6_FREQ 50000000
#define B_6_HAS_IN 0
#define B_6_HAS_OUT 1
#define B_6_HAS_TRI 0
#define B_6_IRQ_TYPE NONE
#define B_6_RESET_VALUE 255

/*
 * Macros for device 'b_7', class 'altera_avalon_pio'
 * The macros are prefixed with 'B_7_'.
 * The prefix is the slave descriptor.
 */
#define B_7_COMPONENT_TYPE altera_avalon_pio
#define B_7_COMPONENT_NAME b_7
#define B_7_BASE 0x100
#define B_7_SPAN 16
#define B_7_END 0x10f
#define B_7_BIT_CLEARING_EDGE_REGISTER 0
#define B_7_BIT_MODIFYING_OUTPUT_REGISTER 0
#define B_7_CAPTURE 0
#define B_7_DATA_WIDTH 8
#define B_7_DO_TEST_BENCH_WIRING 0
#define B_7_DRIVEN_SIM_VALUE 0
#define B_7_EDGE_TYPE NONE
#define B_7_FREQ 50000000
#define B_7_HAS_IN 0
#define B_7_HAS_OUT 1
#define B_7_HAS_TRI 0
#define B_7_IRQ_TYPE NONE
#define B_7_RESET_VALUE 255

/*
 * Macros for device 'sysid_qsys', class 'altera_avalon_sysid_qsys'
 * The macros are prefixed with 'SYSID_QSYS_'.
 * The prefix is the slave descriptor.
 */
#define SYSID_QSYS_COMPONENT_TYPE altera_avalon_sysid_qsys
#define SYSID_QSYS_COMPONENT_NAME sysid_qsys
#define SYSID_QSYS_BASE 0x10000
#define SYSID_QSYS_SPAN 8
#define SYSID_QSYS_END 0x10007
#define SYSID_QSYS_ID 2899645186
#define SYSID_QSYS_TIMESTAMP 1501665651

/*
 * Macros for device 'jtag_uart', class 'altera_avalon_jtag_uart'
 * The macros are prefixed with 'JTAG_UART_'.
 * The prefix is the slave descriptor.
 */
#define JTAG_UART_COMPONENT_TYPE altera_avalon_jtag_uart
#define JTAG_UART_COMPONENT_NAME jtag_uart
#define JTAG_UART_BASE 0x20000
#define JTAG_UART_SPAN 8
#define JTAG_UART_END 0x20007
#define JTAG_UART_IRQ 2
#define JTAG_UART_READ_DEPTH 64
#define JTAG_UART_READ_THRESHOLD 8
#define JTAG_UART_WRITE_DEPTH 64
#define JTAG_UART_WRITE_THRESHOLD 8


#endif /* _ALTERA_HPS_0_H_ */
